fileName <- "household_power_consumption.txt"
con <- file(fileName,open="r")
good1 <- grep("^1/2/2007",readLines(con))
close(con)
con <- file(fileName,open="r")
good2 <- grep("^2/2/2007",readLines(con))
close(con)
start <- good1[1]-1
lasting <- length(good1)+length(good2)
myColNames <- read.table(fileName,sep=";",nrow=1,colClass="character")
myData <- read.table(fileName,sep=";",skip=start,nrow=lasting,col.names=myColNames)
myData$Date_Time <- paste(myData$Date,myData$Time,sep=" ") 
myData$Date_Time <- strptime(myData$Date_Time,"%d/%m/%Y %H:%M:%S")
png(filename="plot3.png",width=480,height=480,units="px")
plot(x=myData$Date_Time,y=myData$Sub_metering_1,xlab="",ylab="Energy sub metering",pch=".")
lines(x=myData$Date_Time,y=myData$Sub_metering_1)
lines(x=myData$Date_Time,y=myData$Sub_metering_2,col="red")
lines(x=myData$Date_Time,y=myData$Sub_metering_3,col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),pch="-",col=c("black","red","blue"))
dev.off()